import Layout from '@/Comps/Layout'
import '@/styles/globals.css'
import Head from "next/head";

export default function App({ Component, pageProps }) {
  return <>
    <Head>
      <title>E-Trade</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      {/* <link rel="icon" href="/logo.png" /> */}
    </Head>

    <Layout>
      <Component {...pageProps} />
    </Layout>
  </>
}
